# Fundamentals of Data Analytics
# Exercise Sheet 1: Introduction to Python, NumPy, and SciPy

---

## Part 1: Python Basics

### Task 1.1: Variables and Data Types

Let's start with some basic Python concepts.

1. Define a variable `age` with an integer value `25`.
2. Define a variable `name` with a string value `"Alice"`.
3. Define a float variable `height` with a value `5.4`.
4. Create a dictionary variable `numbers_dict` containing the numbers from 1 to 5 as keys and their corresponding written forms as values.

In [4]:
# Task 1.1: Define the variables
age = 25
name = "Alice"
height = 5.4
numbers_dict = {"1": "one", "2": "two", "3": "three", "4": "four", "5": "five"}
numbers_dict

{'1': 'one', '2': 'two', '3': 'three', '4': 'four', '5': 'five'}

### Task 1.2: Basic Operations

1. Add 10 to the `age` variable, and store the result in a new variable `new_age`.
2. Create a new variable `description` that includes `name` and `height` in a sentence. Example: "Alice is 5.4 feet tall."

In [ ]:
# Task 1.2: Perform operations
new_age = age + 10
description = f"{name} is {height} feet fall"
print(description)

### Task 1.3: Control Structures

1. Use a `for` loop to create a list of numbers from 1 to 10.
2. Use a list comprehension to create a list of numbers from 1 to 10.
3. Use a `while` loop to calculate the factorial of 5.

In [2]:
# Task 1.3.1: Create a list using a for loop
numbers_list = []
for i in range(1, 10, 1):
    numbers_list.append(i)

print(numbers_list)
...

# Task 1.3.2: Create a list using a list comprehension
...
squares = [x**2 for x in numbers_list]
print(squares)

# Task 1.3.3: Calculate factorial using a while loop
n = 5
factorial = 1
i = 1
while i <= 5:
    factorial *= i
    i += 1
    

print(factorial)
    

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 4, 9, 16, 25, 36, 49, 64, 81]
120


### Task 1.4: Functions

1. Write a function `square` that takes a number as input and returns its square.
2. Write a function `greet` that takes a `name` as input and returns a greeting message.

In [9]:
# Task 1.4: Define and execute the functions
def square(num: int) -> int:
    return num**2

def greet(name: str) -> str:
    return f"Hello {name}!"

print(square(4))
print(greet("Nasrul"))


16
Hello Nasrul!


### Task 1.5: File I/O using the `with open(...)` statement

1. Create a variable `numbers` containing a list of numbers from 0 to 99
2. Write the numbers to a file named `numbers.txt`, each on a different line.
3. Read the contents of `numbers.txt` and print them.

In [13]:
# Task 1.5: File I/O
numbers = []
for i in range(100):
    numbers.append(i)
print(numbers)

# Write numbers to a file
with open("numbers.txt", 'w') as file:
    for num in numbers:
        file.write(f'{num}\n')

# Read and print the contents of the file
with open("numbers.txt", 'r') as file:
    content = file.read()
    print(content)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99



---

## Part 2: NumPy Basics

### Task 2.1: Creating and Manipulating Arrays

1. Create a NumPy array of the first ten positive integers.
2. Reshape this array into a 2x5 matrix.

In [17]:
import numpy as np

# Task 2.1.1: Create array
array_1_to_10 = np.arange(1, 11)
print(array_1_to_10)

# Task 2.1.2: Reshape into 2x5 matrix
matrix_2x5 = np.reshape(array_1_to_10, (2,5))
matrix_2x5

[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Task 2.2: Array Operations

1. Calculate the transpose of `matrix_2x5`.
2. Flatten the matrix back into a 1D array.

In [18]:
# Task 2.2.1: Transpose the matrix
transposed_matrix = np.transpose(matrix_2x5)
print(transposed_matrix)

# Task 2.2.2: Flatten the matrix
flattened_array = matrix_2x5.flatten()
print(flattened_array)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[ 1  2  3  4  5  6  7  8  9 10]


### Task 2.3: Statistical Operations

1. Calculate the mean, median, and standard deviation of the `array_1_to_10`.

In [22]:
# Task 2.3: Statistical operations
mean_value = array_1_to_10.mean()
median_value = np.median(array_1_to_10)
std_dev = array_1_to_10.std()

print(mean_value)
print(median_value)
print(std_dev)

5.5
5.5
2.8722813232690143


---

## Part 3: SciPy Introduction

### Task 3.1: Numerical Integration

1. Use SciPy to integrate the function $f(x) = x^2$ from 0 to 1.

In [24]:
from scipy.integrate import quad

# Task 3.1: Define function and integrate
def f(x):
    return x**2

a = 0
b = 1

integral_value, error = quad(f, a, b)
print(integral_value)
print(error)

0.3333333333333333
3.700743415417188e-15


### Task 3.2: Solving Linear Systems

1. Solve the following system of equations using SciPy:
    - $2x + 3y = 8$
    - $x - y = 1$

In [26]:
from scipy.linalg import solve

# Coefficients matrix
A = np.array([[2, 3],[1, -1]])

# Constants vector
b = np.array([8, 1])

# Solve the system
solution = solve(A, b)
print(solution)

[2.2 1.2]


### Task 3.3: Optimization

1. Find the minimum of the function $f(x) = x^2 + 2x + 1$ using SciPy.

In [29]:
from scipy.optimize import minimize

# Task 3.3: Define function and find minimum
def f_to_minimize(x):
    return x**2 + 2*x + 1

initial_guess = 0
result = minimize(f_to_minimize, initial_guess)

print(result)

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 0.0
        x: [-1.000e+00]
      nit: 2
      jac: [ 0.000e+00]
 hess_inv: [[ 5.000e-01]]
     nfev: 6
     njev: 3


### Exercise 1 Task

In [1]:
list1 = [0] * 5
list2 = [1] * 6

In [2]:
lis3 = list1 + list2

In [3]:
lis3

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]

In [7]:
list4 = list(range(1, 11))

In [8]:
list5 = list4 + lis3

In [9]:
list5

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]

In [10]:
unique = set()
for num in list5:
    unique.add(num)
unique

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [11]:
unique.remove(2)

In [13]:
unique

{0, 1, 3, 4, 5, 6, 7, 8, 9, 10}

In [14]:
unique.add("2")

In [16]:
unique

{0, 1, 10, '2', 3, 4, 5, 6, 7, 8, 9}

In [17]:
unique.add(True)

In [19]:
unique

{0, 1, 10, '2', 3, 4, 5, 6, 7, 8, 9}

In [20]:
# True is 1 and False is 0 and we already have 1 and 0 in the set so adding another True is not possible
# However, in order to do that we would have to convert the set into a list
result_list = list(unique)

In [21]:
result_list

[0, 1, 3, 4, 5, 6, 7, 8, 9, 10, '2']

In [22]:
result_list.append(True)

In [23]:
result_list

[0, 1, 3, 4, 5, 6, 7, 8, 9, 10, '2', True]

In [24]:
# Exercise 3

# Reverse a list without using loops 
li = list(range(1, 10))

In [25]:
li

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
input_index = 2

In [36]:
def reverse_list(input_index: int, li: list) -> list:
    li1 = li[0:input_index]
    li2 = li[input_index + 1: ]
    return li1[::-1] + [li[input_index]] + li2[::-1]

In [37]:
reverse_list(input_index, li)

[2, 1, 3, 9, 8, 7, 6, 5, 4]

### Exercise 4

Exercise 4 — Scrabble - 0 Points - Programming task
Create a function in a script that takes a word and calculates its Scrabble score. Use the following
values for this:
values = {"a": 1, "b": 3, "c": 4, "d": 1, "e": 1, "f": 4, "g": 2, "h": 2, "i": 1, "j":
6, "k": 4, "l": 2, "m": 3, "n": 1, "o": 2, "p": 4, "q": 10, "r": 1, "s": 1, "t":
1, "u": 1, "v": 6, "w": 3, "x": 8, "y": 10, "z": 3, "ä": 6, "ö": 8, "ü": 6}
An example looks like this:
scrabble(’informatikum’)
23
Hint 1: The following should be the first line in your script so that the umlauts are correctly recognized:
# -*- coding: utf-8 -*-
Hint 2: Assume that the entry always consists of lowercase letters.

### Exercise 4 — Scrabble - 0 Points - Programming task
Create a function in a script that takes a word and calculates its Scrabble score. Use the following
values for this:
values = {"a": 1, "b": 3, "c": 4, "d": 1, "e": 1, "f": 4, "g": 2, "h": 2, "i": 1, "j":
6, "k": 4, "l": 2, "m": 3, "n": 1, "o": 2, "p": 4, "q": 10, "r": 1, "s": 1, "t":
1, "u": 1, "v": 6, "w": 3, "x": 8, "y": 10, "z": 3, "ä": 6, "ö": 8, "ü": 6}
An example looks like this:
scrabble(’informatikum’)
23
Hint 1: The following should be the first line in your script so that the umlauts are correctly recognized:
 -*- coding: utf-8 -*-
Hint 2: Assume that the entry always consists of lowercase letters.

In [41]:
values = {"a": 1, "b": 3, "c": 4, "d": 1, "e": 1, "f": 4, "g": 2, "h": 2, "i": 1, "j":
6, "k": 4, "l": 2, "m": 3, "n": 1, "o": 2, "p": 4, "q": 10, "r": 1, "s": 1, "t":
1, "u": 1, "v": 6, "w": 3, "x": 8, "y": 10, "z": 3, "ä": 6, "ö": 8, "ü": 6}

In [42]:
def scrabble_score(s: str) -> int:
    score = 0
    for ch in s:
        score += values[ch]
    return score

In [43]:
scrabble_score("informatikum")

23